type User {
  id: ID!
  email: String!
  password: String!
  level: Level!
  status: Status
  team: Team
  application: Application
}

type Team {
  members: [User!]
}

type File {
  name: String!
  path: String!
}

type Application {
  id: ID!
  firstName: String
  lastName: String
  levelOfStudy: LevelOfStudy
  major: String
  shirtSize: ShirtSize
  gender: Gender
  resume: File
}

type Query {
  user(id: ID!): User!
  application(id: ID!): Application!
  info: String!
}

type Token {
  token: String!
}

type Mutation {
  signUp(email: String!, password: String!): Token!
  logIn(email: String!, password: String!): Token!
  verify(token: String!): Token!
  updateApplication(
    firstName: String
    lastName: String
    levelOfStudy: LevelOfStudy
    major: String
    shirtSize: ShirtSize
    gender: Gender,
    resume: Upload
  ): Application!
  submitApplication(
    firstName: String!
    lastName: String!
    levelOfStudy: LevelOfStudy!
    major: String!
    shirtSize: ShirtSize!
    gender: Gender!
    resume: Upload!
  ): Application!
}

enum Level {
  HACKER
  SPONSOR
  ADMIN
}

enum Status {
  UNVERIFIED
  VERIFIED
  SUBMITTED
  REJECTED
  WAITLISTED
  ACCEPTED
  CONFIRMED
}

enum ShirtSize {
  XSMALL
  SMALL
  MEDIUM
  LARGE
  XLARGE
}

enum LevelOfStudy {
  FRESHMAN
  SOPHOMORE
  JUNIOR
  SENIOR
  SENIORPLUS
}

enum Gender {
  MALE
  FEMALE
  OTHER
  NORESPONSE
}
